
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported fields

[partintro]

--
This document describes the fields that are exported by Metricbeat. They are
grouped in the following categories:

* <<exported-fields-beanstalkd>>
* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-common>>
* <<exported-fields-docker-processor>>
* <<exported-fields-kubernetes-processor>>

--
[[exported-fields-beanstalkd]]
== BeanstalkD fields

beanstalkd module



[float]
== beanstalkd fields




[float]
== info fields

Statistics across the whole beanstalkd instance



[float]
=== `beanstalkd.info.binlog-current-index`

type: long

Is the index of the current binlog file being written to. If binlog is not active this value will be 0


[float]
=== `beanstalkd.info.binlog-max-size`

type: long

Is the maximum size in bytes a binlog file is allowed to get before a new binlog file is opened


[float]
=== `beanstalkd.info.binlog-oldest-index`

type: long

Is the index of the oldest binlog file needed to store the current jobs


[float]
=== `beanstalkd.info.binlog-records-migrated`

type: long

Is the cumulative number of records written as part of compaction


[float]
=== `beanstalkd.info.binlog-records-written`

type: long

Is the cumulative number of records written to the binlog.


[float]
=== `beanstalkd.info.cmd-bury`

type: long

Is the cumulative number of bury commands.


[float]
=== `beanstalkd.info.cmd-delete`

type: long

Is the cumulative number of delete commands.


[float]
=== `beanstalkd.info.cmd-ignore`

type: long

Is the cumulative number of ignore commands.


[float]
=== `beanstalkd.info.cmd-kick`

type: long

Is the cumulative number of kick commands.


[float]
=== `beanstalkd.info.cmd-list-tube-used`

type: long

Is the cumulative number of list-tube-used commands.


[float]
=== `beanstalkd.info.cmd-list-tubes`

type: long

Is the cumulative number of list-tubes commands.


[float]
=== `beanstalkd.info.cmd-list-tubes-watched`

type: long

Is the cumulative number of list-tubes-watched commands.


[float]
=== `beanstalkd.info.cmd-pause-tube`

type: long

Is the cumulative number of pause-tube commands.


[float]
=== `beanstalkd.info.cmd-peek`

type: long

Is the cumulative number of peek commands.


[float]
=== `beanstalkd.info.cmd-peek-buried`

type: long

Is the cumulative number of peek-buried   commands.


[float]
=== `beanstalkd.info.cmd-peek-delayed`

type: long

Is the cumulative number of peek-delayed commands.


[float]
=== `beanstalkd.info.cmd-peek-ready`

type: long

Is the cumulative number of peek-ready commands.


[float]
=== `beanstalkd.info.cmd-put`

type: long

Is the cumulative number of put commands.


[float]
=== `beanstalkd.info.cmd-release`

type: long

Is the cumulative number of release commands.


[float]
=== `beanstalkd.info.cmd-reserve`

type: long

Is the cumulative number of reserve commands.


[float]
=== `beanstalkd.info.cmd-reserve-with-timeout`

type: long

Is the cumulative number of reserve-with-timeout commands.


[float]
=== `beanstalkd.info.cmd-stats`

type: long

Is the cumulative number of stats commands.


[float]
=== `beanstalkd.info.cmd-stats-job`

type: long

Is the cumulative number of stats-job commands.


[float]
=== `beanstalkd.info.cmd-stats-tube`

type: long

Is the cumulative number of stats-tube commands.


[float]
=== `beanstalkd.info.cmd-touch`

type: long

Is the cumulative number of touch commands.


[float]
=== `beanstalkd.info.cmd-use`

type: long

Is the cumulative number of use commands.


[float]
=== `beanstalkd.info.cmd-watch`

type: long

Is the cumulative number of watch commands.


[float]
=== `beanstalkd.info.current-connections`

type: long

Is the number of currently open connections.


[float]
=== `beanstalkd.info.current-jobs-buried`

type: long

Is the number of currently burried jobs connections.


[float]
=== `beanstalkd.info.current-jobs-delayed`

type: long

Is the number of currently delayed jobs connections.


[float]
=== `beanstalkd.info.current-jobs-ready`

type: long

Is the number of currently ready jobs connections.


[float]
=== `beanstalkd.info.current-jobs-reserved`

type: long

Is the number of currently reserved jobs connections.


[float]
=== `beanstalkd.info.current-jobs-urgent`

type: long

Is the number of currently urgent jobs connections.


[float]
=== `beanstalkd.info.current-producers`

type: long

Is the number of open connections that have each issued at least one put command.


[float]
=== `beanstalkd.info.current-tubes`

type: long

Is the number of currently-existing tubes.


[float]
=== `beanstalkd.info.current-waiting`

type: long

Is the number of open connections that have issued a reserve command but not yet received a response.


[float]
=== `beanstalkd.info.current-workers`

type: long

Is the number of open connections that have each issued at least one reserve command.


[float]
=== `beanstalkd.info.job-timeouts`

type: long

Is the cumulative count of times a job has timed out.


[float]
=== `beanstalkd.info.max-job-size`

type: long

Is the maximum number of bytes in a job.


[float]
=== `beanstalkd.info.pid`

type: long

Is the process id of the server.


[float]
=== `beanstalkd.info.total-jobs`

type: long

Is the cumulative count of jobs created in this tube in the current beanstalkd process.


[float]
=== `beanstalkd.info.total-connections`

type: long

Is the cumulative count of connections.


[float]
=== `beanstalkd.info.uptime`

type: long

Is the number of seconds since this server process started running.


[float]
=== `beanstalkd.info.hostname`

type: keyword

The hostname of the machine as determined by uname.


[float]
=== `beanstalkd.info.id`

type: keyword

Is a random id string for this server process, generated when each beanstalkd process starts.


[float]
=== `beanstalkd.info.version`

type: keyword

Is the version string of the server.


[float]
=== `beanstalkd.info.rusage-stime`

type: scaled_float

Is the cumulative system CPU time of this process in seconds and microseconds.


[float]
=== `beanstalkd.info.rusage-utime`

type: scaled_float

Is the cumulative user CPU time of this process in seconds and microseconds.


[float]
== tube fields

Shows the details stats about a specific tube



[float]
=== `beanstalkd.tube.name`

type: keyword

Is the tube's name.


[float]
=== `beanstalkd.tube.current-jobs-buried`

type: long

Is the number of buried jobs in this tube.


[float]
=== `beanstalkd.tube.current-jobs-delayed`

type: long

Is the number of delayed jobs in this tube.


[float]
=== `beanstalkd.tube.current-jobs-ready`

type: long

Is the number of jobs in the ready queue in this tube.


[float]
=== `beanstalkd.tube.current-jobs-reserved`

type: long

Is the number of jobs reserved by all clients in this tube.


[float]
=== `beanstalkd.tube.current-jobs-urgent`

type: long

Is the number of ready jobs with priority < 1024 in this tube.


[float]
=== `beanstalkd.tube.total-jobs`

type: long

Is the cumulative count of jobs created in this tube in the current beanstalkd process.


[float]
=== `beanstalkd.tube.cmd-delete`

type: long

Is the cumulative number of delete commands for this tube.


[float]
=== `beanstalkd.tube.cmd-pause-tube`

type: long

Is the cumulative number of pause-tube commands for this tube.


[float]
=== `beanstalkd.tube.pause`

type: long

Is the number of seconds the tube has been paused for.


[float]
=== `beanstalkd.tube.pause-time-left`

type: long

Is the number of seconds until the tube is un-paused.


[float]
=== `beanstalkd.tube.current-using`

type: long

Is the number of open connections that are currently using this tube.


[float]
=== `beanstalkd.tube.current-watching`

type: long

Is the number of open connections that are currently watching this tube.


[float]
=== `beanstalkd.tube.current-waiting`

type: long

Is the number of open connections that have issued a reserve command while watching this tube but not yet received a response..


[[exported-fields-beat]]
== Beat fields

Contains common beat fields available in all event types.



[float]
=== `beat.name`

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== `beat.hostname`

The hostname as returned by the operating system on which the Beat is running.


[float]
=== `beat.timezone`

The timezone as returned by the operating system on which the Beat is running.


[float]
=== `beat.version`

The version of the beat that generated this event.


[float]
=== `@timestamp`

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== `tags`

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== `fields`

type: object

Contains user configurable fields.


[float]
== error fields

Error fields containing additional info in case of errors.



[float]
=== `error.message`

type: text

Error message.


[float]
=== `error.code`

type: long

Error code.


[float]
=== `error.type`

type: keyword

Error type.


[[exported-fields-cloud]]
== Cloud provider metadata fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== `meta.cloud.provider`

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== `meta.cloud.instance_id`

Instance ID of the host machine.


[float]
=== `meta.cloud.instance_name`

Instance name of the host machine.


[float]
=== `meta.cloud.machine_type`

example: t2.medium

Machine type of the host machine.


[float]
=== `meta.cloud.availability_zone`

example: us-east-1c

Availability zone in which this host is running.


[float]
=== `meta.cloud.project_id`

example: project-x

Name of the project in Google Cloud.


[float]
=== `meta.cloud.region`

Region in which this host is running.


[[exported-fields-common]]
== Common fields

Contains common fields available in all event types.



[float]
=== `metricset.module`

The name of the module that generated the event.


[float]
=== `metricset.name`

The name of the metricset that generated the event.


[float]
=== `metricset.host`

Hostname of the machine from which the metricset was collected. This field may not be present when the data was collected locally.


[float]
=== `metricset.rtt`

type: long

required: True

Event round trip time in microseconds.


[float]
=== `metricset.namespace`

type: keyword

Namespace of dynamic metricsets.


[float]
=== `type`

example: metricsets

required: True

The document type. Always set to "doc".


[[exported-fields-docker-processor]]
== Docker fields

Docker stats collected from Docker.




[float]
=== `docker.container.id`

type: keyword

Unique container id.


[float]
=== `docker.container.image`

type: keyword

Name of the image the container was built on.


[float]
=== `docker.container.name`

type: keyword

Container name.


[float]
=== `docker.container.labels`

type: object

Image labels.


[[exported-fields-kubernetes-processor]]
== Kubernetes fields

Kubernetes metadata added by the kubernetes processor




[float]
=== `kubernetes.pod.name`

type: keyword

Kubernetes pod name


[float]
=== `kubernetes.namespace`

type: keyword

Kubernetes namespace


[float]
=== `kubernetes.node.name`

type: keyword

Kubernetes node name


[float]
=== `kubernetes.labels`

type: object

Kubernetes labels map


[float]
=== `kubernetes.annotations`

type: object

Kubernetes annotations map


[float]
=== `kubernetes.container.name`

type: keyword

Kubernetes container name


[float]
=== `kubernetes.container.image`

type: keyword

Kubernetes container image


