package info

import (
	s "github.com/elastic/beats/libbeat/common/schema"
	c "github.com/elastic/beats/libbeat/common/schema/mapstrstr"
)

var schema = s.Schema{
	"binlog-current-index":     c.Int("binlog-current-index"),
	"binlog-max-size":          c.Int("binlog-max-size"),
	"binlog-oldest-index":      c.Int("binlog-oldest-index"),
	"binlog-records-migrated":  c.Int("binlog-records-migrated"),
	"binlog-records-written":   c.Int("binlog-records-written"),
	"cmd-bury":                 c.Int("cmd-bury"),
	"cmd-delete":               c.Int("cmd-delete"),
	"cmd-ignore":               c.Int("cmd-ignore"),
	"cmd-kick":                 c.Int("cmd-kick"),
	"cmd-list-tube-used":       c.Int("cmd-list-tube-used"),
	"cmd-list-tubes":           c.Int("cmd-list-tubes"),
	"cmd-list-tubes-watched":   c.Int("cmd-list-tubes-watched"),
	"cmd-pause-tube":           c.Int("cmd-pause-tube"),
	"cmd-peek":                 c.Int("cmd-peek"),
	"cmd-peek-buried":          c.Int("cmd-peek-buried"),
	"cmd-peek-delayed":         c.Int("cmd-peek-delayed"),
	"cmd-peek-ready":           c.Int("cmd-peek-ready"),
	"cmd-put":                  c.Int("cmd-put"),
	"cmd-release":              c.Int("cmd-release"),
	"cmd-reserve":              c.Int("cmd-reserve"),
	"cmd-reserve-with-timeout": c.Int("cmd-reserve-with-timeout"),
	"cmd-stats":                c.Int("cmd-stats"),
	"cmd-stats-job":            c.Int("cmd-stats-job"),
	"cmd-stats-tube":           c.Int("cmd-stats-tube"),
	"cmd-touch":                c.Int("cmd-touch"),
	"cmd-use":                  c.Int("cmd-use"),
	"cmd-watch":                c.Int("cmd-watch"),
	"current-connections":      c.Int("current-connections"),
	"current-jobs-buried":      c.Int("current-jobs-buried"),
	"current-jobs-delayed":     c.Int("current-jobs-delayed"),
	"current-jobs-ready":       c.Int("current-jobs-ready"),
	"current-jobs-reserved":    c.Int("current-jobs-reserved"),
	"current-jobs-urgent":      c.Int("current-jobs-urgent"),
	"current-producers":        c.Int("current-producers"),
	"current-tubes":            c.Int("current-tubes"),
	"current-waiting":          c.Int("current-waiting"),
	"current-workers":          c.Int("current-workers"),
	"job-timeouts":             c.Int("job-timeouts"),
	"max-job-size":             c.Int("max-job-size"),
	"pid":                      c.Int("pid"),
	"total-jobs":               c.Int("total-jobs"),
	"total-connections":        c.Int("total-connections"),
	"uptime":                   c.Int("uptime"),
	"hostname":                 c.Str("hostname"),
	"id":                       c.Str("id"),
	"version":                  c.Str("version"),
	"rusage-stime":             c.Float("rusage-stime"),
	"rusage-utime":             c.Float("rusage-utime"),
}
